---

  - name: purge nodejs
    apt: name=nodejs purge=yes
  - name: purge npm
    apt: name=npm purge=yes
  - name: update_apt_repository
    apt: update_cache=yes
  - name: Install add properties
    apt: name=python-software-properties force=yes state=present
  - name: add repository to vm
    apt_repository: repo='ppa:chris-lea/node.js'
  - name: update_apt_repository
    apt: update_cache=yes
  - name: install nodejs
    apt: name=nodejs state=latest 
